config/routes.rb
Rails.application.routes.draw do

  get 'cart/index'


  devise_for :users
  get 'search', to: 'search#index'
  post 'search', to: 'search#index'
  root 'home#index'

  resources :reviews
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true, greater_than: 0}

  belongs_to :user
  has_many :reviews

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    format("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/search.rb
class Search < ApplicationRecord

  require 'nokogiri'

  attr_reader :dom, :title, :image, :price

  def initialize(params)

    @title = []
    @image = []
    @price = []

    production_app_id = "JonasErt-ItemsPul-PRD-d09141381-de141c97"
    url = "http://svcs.ebay.com/services/search/FindingService/v1"

    query_search = params.split(" ").join("%20")

    url += "?OPERATION-NAME=findItemsByKeywords"
    url += "&keywords=#{query_search}"
    url += "&SECURITY-APPNAME=" + production_app_id

    response = HTTParty.get url
    @dom = Nokogiri::HTML(response.body)

    list = @dom.css("title")
    list.each_with_index do |item, index|
      @title.push item.content
      @image.push @dom.css('galleryurl')[index].content
      @price.push  @dom.css('currentprice')[index].content
    end
  end

  # def titles
  #   output = ""
  #   list = @dom.css("title")
  #   list.each_with_index do |item, index|
  #     output += "<li>#{item.content}</li>"
  #     output += "<li>#{@dom.css('galleryurl')[index]}</li>"
  #     output += "<li>$#{@dom.css('currentprice')[index]}</li>"
  #   end
  #   output
  # end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # included do
  #   before_filter :authenticate_user!, except: [:index, :show]
  # end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image, :description, :price_in_cents)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = current_user.reviews.build
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = current_user.reviews.build(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :product_id)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  	@params = params[:query]
    @search = Search.new(@params)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/cart/index.html.erb
<h1>Cart#index</h1>
<p>Find me in app/views/cart/index.html.erb</p>

app/views/home/index.html.erb
<%= link_to 'products/3' do%>
<div id="main-section-products">
	<h1 class="best-seller">SAHARA.com</h1>
	<h2 class="product-name">Apple Watch 2-Sport Edition</h2>
</div>
<% end %>

<div class="info">
	<div class="info-item">
		<img class="info-item-image" src="https://d30y9cdsu7xlg0.cloudfront.net/png/2524-200.png" alt="money">
		<h2>The largest peer-to-peer marketplace</h2>
		<p>Looking for something to buy or sell without dealing with retail? Sahara offers the largest community of buyers and sellers for any item.</p>
	</div>
	<div class="info-item">
		<img class="info-item-image" src="https://d30y9cdsu7xlg0.cloudfront.net/png/34255-200.png" alt="Package">
		<h2>Low Shipping Costs for high volume transactions</h2>
		<p>Sahara's logistical operations provide customers with the lowest shipping costs in the market. We even beat eBay, and that other competitor named after a large rainforest.</p>
	</div>
	<div class="info-item">
		<img class="info-item-image" src="https://d30y9cdsu7xlg0.cloudfront.net/png/547815-200.png" alt="Blaster">
		<h2>Han Solo shot first, and George Lucas knows it.</h2>
		<p>I've ran out of ideas for the site, but this is definitely always on my mind. Why does George Lucas INSIST that Greedo shot first??? The original film clearly shows otherwise.</p>
	</div>
</div>
<div class="blank">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta name ="viewport" content="width=device-width, initial-scale = 1">
    <title>Sahara.com</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" type= "text/css" href="assets/normalize.css">
     <link rel="stylesheet" type= "text/css" href="style.css">
  </head>

  <body>
    <header class="nav-bar">
    <nav>
      <ul class="nav-bar__menu">
        <li class="nav-bar__menu-logo"><%= link_to 'SAHARA.com', root_path %></li>
        <%= form_tag("/search", method: "get") do %>
          <%= text_field_tag(:query,nil, placeholder: 'Search in Sahara')%>
        <% end %>
        <!-- <form action= "search" method ="get">
          <li class ="nav-bar__menu-item"><input type="text" class="nav-bar__menu-item-input" placeholder= "Search in Sahara" id = "query"/></li>
          <li class ="nav-bar__menu-item"><input type="submit" value="Submit"></li>
        </form> -->
        <% if user_signed_in? %>
        <li class="nav-bar__menu-welcome">Welcome, <%= current_user.email %></li>
        <li class ="nav-bar__menu-account"><%= link_to 'Account', edit_user_registration_path %></li>
        <li class ="nav-bar__menu-sign-out"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
        <li class ="nav-bar__menu-item"><%= link_to 'Login', new_user_session_path %></li>
        <li class ="nav-bar__menu-item"><%= link_to 'Sign up', new_user_registration_path %></li>
      <% end %>
      </ul>
    </nav>
  </header>
  <div id="slider">
  </div>
  <div id ="container">
    <%= yield %>
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
  </div>
  <footer>
    <ul class="nav-bar__menu">
      <li class="nav-bar__menu-item"><a href="#">About</a></li>
    </ul>
  </footer>


  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :product_image %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :price_in_cents %>
    <%= form.number_field :price_in_cents, id: :product_price_in_cents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1 >Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Best Sellers</h1>

<table>
  <!-- <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->

  <tbody>
    <% @products.each do |product| %>
      <tr>
        
        <td><%= image_tag product.image %></td>
        <!-- <td><%= product.description %></td> -->
        <td><%= product.name %></td>
        <td>$<%= product.formatted_price %></td>
        <td><%= link_to 'Show', product %></td>
        <% if product.user == current_user %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class ="product-name1">
  <strong><%= @product.name %></strong>
</h2>


<div id="featured-product-img">
    <%= image_tag @product.image %>
</div>
<div id ="featured-product-price">
    $<%= @product.formatted_price %>
</div>

<div id ="featured-product">
    <%= @product.description %>
</div>


<div id ="featured-product-cart">
<button class="add-to-cart" type="button" name="button">Add to Cart</button>
</div>

<% @product.reviews.each do |review| %>
  <div id ="featured-product">
    <h3>Reviews</h3>
    <strong><%= review.user.email %></strong><br>
    <%= review.comment %>
    <br>
    Added on: <%= review.created_at %>
  </div id ="featured-product">
<% end %>
<div id ="featured-product">
<h3>New Review</h3>
<%= render 'reviews/form' %>
</div>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/reviews/_form.html.erb
<%= form_with(model: @review, local: true) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <div class="field">
      <%= form.label :comment %>
      <%= form.text_area :comment%>
    </div>

  <% if @product.nil? %>
     <div class="field">
       <%= form.label :product_id %><br>
       <%= form.text_field :product_id %>
     </div>
    <% else %>
     <%= form.hidden_field :product_id, value: @product.id %>
    <% end %>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% else %>
    <p>Want to review this item?</p><br>
    <%= link_to 'Login', new_user_session_path %>
    <%= link_to 'Sign up', new_user_registration_path %>
  <% end %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.product %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product.name %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |

<% if @review.product.nil? %>
  <%= link_to 'Back', reviews_path %>

<% else %>
  <%= link_to 'Back', @review.product %>
<% end %>

app/views/search/index.html.erb
<div id ="search-main-title"><h1 >Search for "<%= params[:query] %>" in Sahara</h1></div>

<% if @search.title[0].to_s =="" %>
	<h3>Has no results</h3>
<% else %>
	<% (0..20).each do |idx| %>
		<section id="sections">

			<div class ="search-picture1">
				<%= image_tag @search.image[idx].to_s %>
			</div>
			<div class ="search-description1">
				<ul>
					<li class="a-title"><%= @search.title[idx] %></li>
					<li class="a-price">$<%= @search.price[idx] %></li>
					<li class="a-button"><button type="button" name="button">Buy with One-Click</button></li>
					<li class="thank-you">Thank you for your purchase!</li>
				</ul>
			</div>
		</section>
	<% end %>
<% end %>